#pragma once

enum SCENEID { SCENE_LOGO, SCENE_MENU, SCENE_GAME, SCENE_EDITOR, SCENE_END };
enum OBJID { OBJ_PLAYER, OBJ_ENEMY, OBJ_PROJECTILE, OBJ_UI, OBJ_END };
enum DIRID { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };