#pragma once

enum EDITORID { STAGE1_1, STAGE1_2, STAGE_BOSS, STAGE_END };

enum SCENEID { SCENE_LOGO, SCENE_MENU, SCENE_STAGE1_1, SCENE_STAGE1_2, SCENE_BOSS_STAGE, SCENE_EDITOR, SCENE_END };

enum OBJID { OBJ_ITEM, OBJ_ENEMY, OBJ_NPC, OBJ_PLAYER, OBJ_PROJECTILE, OBJ_END };

enum TILEID { TILE_NORMAL, TILE_COLLISION, TILE_END };

enum UIID { UI_BUTTON, UI_DAMAGE_NUMBERS, UI_COMBO_COUNTER, UI_HEALTH_BAR, UI_HEALTH_BAR_BOSS, UI_ENERGY_BAR, UI_REWARD, UI_END };

enum DIRID { DIR_LEFT, DIR_RIGHT, DIR_END };

enum CHANNELID { CHANNEL_BGM, CHANNEL_SYSTEM, CHANNEL_EFFECT, CHANNEL_VOICE, CHANNEL_END };