#pragma once

enum DIRID { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };
enum OBJID { OBJ_PLAYER, OBJ_ENEMY, OBJ_PROJECTILE, OBJ_END };
enum SCENEID { SCENE_LOGO, SCENE_MENU, SCENE_GAME, SCENE_EDITOR, SC_END };